# Generated by Django 3.2.2 on 2021-05-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=60)),
                ('drink_instructions', models.CharField(max_length=510)),
                ('drink_image', models.URLField(blank=True, default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_category', to='drinkTeamClub.category')),
                ('favorites', models.ManyToManyField(blank=True, related_name='drink_in_favorite', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='drink_ingredients', to='drinkTeamClub.Ingredient')),
            ],
        ),
    ]
