# Generated by Django 3.2.2 on 2021-05-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkTeamClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_instructions',
            field=models.CharField(max_length=1010),
        ),
    ]
