# Generated by Django 3.2 on 2021-05-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinkTeamClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='drink_in_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='drink_ingredients', to='drinkTeamClub.Ingredient'),
        ),
    ]
