# Generated by Django 3.2.2 on 2021-05-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkTeamClub', '0003_alter_ingredient_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=60),
        ),
    ]
