# Generated by Django 3.2.2 on 2021-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkTeamClub', '0004_alter_ingredient_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_instructions',
            field=models.CharField(max_length=510),
        ),
    ]
